env:
  browser: true
  es6: true
  node: true
  amd: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2016
  sourceType: module
rules:
  no-console: off
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
